// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8QG7_Znf94LiHdVIhkB595aBKDeAznpY',
    appId: '1:706018889242:web:84941a722fa125da118ba3',
    messagingSenderId: '706018889242',
    projectId: 'clever-tech-flutter',
    authDomain: 'clever-tech-flutter.firebaseapp.com',
    storageBucket: 'clever-tech-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFOdP2n9ca76OhLC-BleUgZdPQwHQ-it8',
    appId: '1:706018889242:android:3489c055c09e419e118ba3',
    messagingSenderId: '706018889242',
    projectId: 'clever-tech-flutter',
    storageBucket: 'clever-tech-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvuF8Lc6Ls2-OrMb5unKpLUbNnD7BkQ_c',
    appId: '1:706018889242:ios:a3f3d659c16b1422118ba3',
    messagingSenderId: '706018889242',
    projectId: 'clever-tech-flutter',
    storageBucket: 'clever-tech-flutter.appspot.com',
    iosClientId: '706018889242-ktn8584dn4dt980hl3ht34cm3f6gcna4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleverTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvuF8Lc6Ls2-OrMb5unKpLUbNnD7BkQ_c',
    appId: '1:706018889242:ios:82c65db383fc55ca118ba3',
    messagingSenderId: '706018889242',
    projectId: 'clever-tech-flutter',
    storageBucket: 'clever-tech-flutter.appspot.com',
    iosClientId: '706018889242-2uh4vtf4mj5oj78rn1ibvl1td2bd437h.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleverTech.RunnerTests',
  );
}
